# Generated by Django 5.2.4 on 2025-09-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0007_delete_watchsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(max_length=200)),
                ('quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p HD'), ('1080p', '1080p Full HD'), ('4K', '4K Ultra HD')], default='720p', max_length=10)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.language')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.moviesubtitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('watch_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.watchsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('watch_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.watchsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
