# Generated by Django 5.2.6 on 2025-09-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefile',
            name='quality',
            field=models.CharField(choices=[('480p', '480p'), ('720p', '720p HD'), ('1080p', '1080p Full HD'), ('4K', '4K Ultra HD')], default='720p', max_length=10),
        ),
    ]
