# Generated by Django 5.2.4 on 2025-09-12 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviefile_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=200)),
                ('quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p HD'), ('1080p', '1080p Full HD'), ('4K', '4K Ultra HD')], default='720p', max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.language')),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.moviesubtitle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
