# Generated by Django 5.2.6 on 2025-09-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_watchsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchsession',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
