# Generated by Django 5.2.4 on 2025-09-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_watchsession_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchSession',
        ),
    ]
